# Étape 1 : Construction (Builder)
FROM node:18-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Étape 2 : Serveur Web (Production)
FROM nginx:alpine
# On copie la configuration Nginx personnalisée (on va la créer juste après)
COPY nginx.conf /etc/nginx/conf.d/default.conf
# On copie les fichiers construits depuis l'étape 1 vers le dossier de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]